### ISSUE TITLE
Installation of the ce edge channel on Ubuntu fails

### ISSUE THREAD

**Issue by robertpeteuil** [avinetworks/ansible-role-docker#8]
I submitted pull request #7 to fix this. 

I’ll provide more detail here:

This problem is caused by the task that installs ce edge on Ubuntu (the last task in “tasks/ce/os/ubuntu.yml”). It calls the “yum” installation handler instead of the “apt” installation handler.

It becomes obvious that this is a typo if the file is viewed in its entirety.  You’ll notice that all tasks are “apt” based, except the last line that notifies a “yum” handler (which fails on non-yum systems), and the correct “apt installation handler” exists and works.

**Comment by ericsysmin** [comment]
Merged.
